version: '3.8'

networks:
  public-network:
    driver: overlay
    internal: false
    name: "{{ public_network_name }}"

secrets:
  cloudflare_dns_api_token:
    external: true

services:
  traefik:
    image: "{{ traefik_image }}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./:/certs/
    secrets:
      - cloudflare_dns_api_token
    environment:
      TZ: "{{ timezone }}"
      CF_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_dns_api_token
    networks:
      - public-network
    dns:
      - 1.1.1.1
      - 1.0.0.1
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.proxy == true
      update_config:
        parallelism: 1
        order: start-first
      restart_policy:
        condition: on-failure
      labels:
        # core
        - traefik.enable=true
        - traefik.docker.network={{ public_network_name }}
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        # http
        - traefik.http.routers.traefik.entrypoints=web_insecure
        - traefik.http.routers.traefik.rule=Host(`{{ traefik_http_route }}`)
        - traefik.http.routers.traefik.service=api@internal
        # tls
        - traefik.http.routers.traefik.tls=false
        - traefik.http.routers.traefik.tls.domains[0].main={{ domain_name }}
        - traefik.http.routers.traefik.tls.domains[0].sans=*.{{ domain_name }}